(function(){
  const qEl = document.getElementById('q');
  const btn = document.getElementById('searchBtn');
  const status = document.getElementById('status');
  const results = document.getElementById('results');

  // If required elements are missing on this page, do nothing
  if(!qEl || !btn || !status || !results) return;

  function setLoading(on, text){
    status.innerHTML = '';
    if(on){
      const div = document.createElement('div'); div.className = 'loading';
      div.innerHTML = '<div class="spinner"></div><div>' + (text||'Thinking...') + '</div>';
      status.appendChild(div);
    }
  }

  function renderResult(data){
    results.innerHTML = '';
    if(!data){ results.innerHTML = '<div class="card">No results</div>'; return; }

    // Order: main answer, additional info (hidden by default), images, examples, summary
    const sections = [];
    const mainAnswer = data.answer || data.mainThings || data.block1_main_ideas || data.block1 || '';
    if(mainAnswer) sections.push({ title: 'Блок 1: Основной ответ', body: mainAnswer });
    if(data.info || data.block2 || data.block2_formulas) sections.push({ title: 'Блок 2: Подробности', body: (data.block2_formulas || data.block2 || data.info || '') , hidden:true });
    if(Array.isArray(data.images) && data.images.length) sections.push({ title: 'Images', images: data.images });
    if(data.examples) sections.push({ title: 'Examples', body: data.examples });
    if(data.summary) sections.push({ title: 'Summary', body: data.summary });

    sections.forEach(s=>{
      const card = document.createElement('div'); card.className = 'card';
      const h = document.createElement('div'); h.innerHTML = '<strong>'+escapeHtml(s.title)+'</strong>';
      card.appendChild(h);
      if(s.hidden){
        // hidden block: add toggle button
        const toggle = document.createElement('button'); toggle.className='small-btn'; toggle.textContent = 'Показать подробности'; toggle.style.marginTop='8px';
        const body = document.createElement('div'); body.style.display = 'none'; body.style.marginTop = '8px'; body.style.whiteSpace = 'pre-wrap'; body.textContent = s.body || '';
        toggle.addEventListener('click', ()=>{
          if(body.style.display === 'none'){ body.style.display = ''; toggle.textContent = 'Скрыть подробности'; }
          else { body.style.display = 'none'; toggle.textContent = 'Показать подробности'; }
        });
        // auto-open if long or formula-like
        try{ if(String(s.body||'').trim().length > 120 || /formula|формул|=/.test(String(s.body||''))){ body.style.display = ''; toggle.textContent = 'Скрыть подробности'; } }catch(e){}
        card.appendChild(toggle); card.appendChild(body);
      } else {
        if(s.body){ const b = document.createElement('div'); b.style.marginTop='8px'; b.style.whiteSpace='pre-wrap'; b.textContent = s.body; card.appendChild(b); }
      }
      if(s.images){
        const wrap = document.createElement('div'); wrap.style.display='flex'; wrap.style.gap='8px'; wrap.style.marginTop='8px';
        s.images.forEach(url=>{ const im = document.createElement('img'); im.src = url; im.style.width='100px'; im.style.height='70px'; im.style.objectFit='cover'; im.style.borderRadius='8px'; wrap.appendChild(im); });
        card.appendChild(wrap);
      }
      results.appendChild(card);
    });

    // Answer + key points card
    const ansCard = document.createElement('div'); ansCard.className='card';
    ansCard.innerHTML = '<strong>Explanation</strong><div style="margin-top:8px;white-space:pre-wrap">'+escapeHtml(data.answer||'')+'</div>';
    const kpCard = document.createElement('div'); kpCard.style.marginTop='12px'; kpCard.innerHTML = '<strong>Key points</strong>';
    const kpList = document.createElement('div'); kpList.className = 'keypoints';
    (data.keyPoints||[]).forEach(kp=>{ const el = document.createElement('div'); el.className='kp'; el.textContent = kp; kpList.appendChild(el); });
    kpCard.appendChild(kpList); ansCard.appendChild(kpCard);
    results.appendChild(ansCard);

    // Flashcards generated by AI (animated)
    const flashWrap = document.createElement('div'); flashWrap.className='flashcards-row';
    (data.flashcards||[]).forEach((fc, idx)=>{
      const f = document.createElement('div'); f.className='flip-card';
      f.innerHTML = `<div class="flip-card-inner"><div class="flip-card-front"><div class="flashcard-title">${escapeHtml(fc.front)}</div><div class="flashcard-body">Tap to flip</div></div><div class="flip-card-back"><div class="flashcard-title">${escapeHtml(fc.front)}</div><div class="flashcard-body">${escapeHtml(fc.back)}</div></div></div>`;
      // toggle on click/touch
      f.addEventListener('click', ()=>{ f.classList.toggle('flipped'); });
      // if card has an id (saved), show a small delete button
      if(fc && fc.id){
        const del = document.createElement('button'); del.className = 'small-btn'; del.textContent = 'Delete';
        del.style.position = 'absolute'; del.style.right = '8px'; del.style.top = '8px'; del.style.zIndex = '10';
        del.addEventListener('click', async (ev)=>{
          ev.stopPropagation();
          if(!confirm('Удалить эту флэшкарту?')) return;
          try{
            const resp = await fetch('/api/flashcards/' + encodeURIComponent(fc.id), { method: 'DELETE' });
            if(resp.ok){ f.remove(); } else { alert('Delete failed'); }
          }catch(e){ alert('Delete failed'); }
        });
        f.style.position = 'relative';
        f.appendChild(del);
      }
      flashWrap.appendChild(f);
    });
    if((data.flashcards||[]).length) results.appendChild(flashWrap);
  }

  function escapeHtml(s){ return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }

  async function doSearch(){
    const q = (qEl.value||'').trim();
    if(!q) return;
    setLoading(true,'Searching...'); results.innerHTML='';
    try{
      const res = await fetch('/api/search', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ query: q }) });
      const j = await res.json().catch(()=>({ error: 'invalid_json' }));
      setLoading(false);
      if(!res.ok){ status.textContent = 'Error: ' + (j && j.error ? j.error : res.status); return; }
      renderResult(j);
    }catch(e){ setLoading(false); status.textContent = 'Network error'; }
  }

  btn.addEventListener('click', doSearch);
  qEl.addEventListener('keydown', (e)=>{ if(e.key === 'Enter') doSearch(); });
})();
